name: Supabase Backup

on:
  schedule:
    - cron: "0 3 * * *" # Щодня о 03:00 UTC
  workflow_dispatch: # Дозволяє запуск вручну

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Dump Supabase database
        run: |
          pg_dump --clean --if-exists --no-owner \
            --dbname="${{ secrets.SUPABASE_DB_URL }}" \
            > backup.sql

      - name: Upload backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backup.sql
